### ISSUE TITLE
Ozone DB Hardfaults on Windows

### ISSUE THREAD

**Issue by RichardKroesen** [Hoog-V/MIC5#1]
Nice work @Hoog-V but I'm stubborn to keep banging my head on nonesense windows issues. Anyways, I found out that the order of the link flags and some could be removed. 

I'm not sure whether the following change is compatible with Linux (hope so). But on windows this solves the hardfault issues during debugging the mcu. 

**startup/arm_gcc.cmake:** 
last part
```
add_link_options(-T ${LINKER_SCRIPT}
                -mthumb
                -mcpu=${MCPU}
                -specs=nano.specs 
                -Wl,--gc-sections
                --specs=nosys.specs
                -Wl,--print-memory-usage
                -lm
                -Wl,-Map=${PROJECT_BINARY_DIR}/${PROJECT_NAME}.map)
add_link_options(-T ${LINKER_SCRIPT} -static)
```

**Comment by Hoog-V** [comment]
Tomorrow, I will test and merge your changes. 

Thank you very much for your perseverance! 

Good job!

Victor

P.S. I will certainly credit you now at top of this cmake file. I think this is fair for the head banging you went through getting this to work!

**Comment by Hoog-V** [comment]
Merged, and added some additional optimizations such as removing the nosys.specs line. This way the linker warnings about unimplemented stdlib functions are gone. As they are secretly implemented by the toolchain as empty functions :) This is good as we don't need printf, c exceptions, file descriptors and the like.. Again Thank you very much for your contribution!
